"use client";

export default function Home() {
  return (
    <main className="relative h-screen">
      <h1 className="font-poppins">Hello world</h1>
      <button
        onClick={async () => {
          const _ = (await import("lodash")).default;
          console.log("-------------");
          const users = [{ name: "c" }, { name: "b" }, { name: "a" }];
          const sortedUsers = _.orderBy(users, ["name"]);

          console.log(sortedUsers);
        }}
      >
        Show
      </button>
    </main>
  );
}

// export default async function Home() {
//   const session = await getServerSession(authOptions);
//   return (
//     <main className="relative h-screen">
//       <h1 className="font-poppins">
//         Hello {session && <span>{session.user?.name}</span>}!
//       </h1>

//       <HeavyComponent></HeavyComponent>
//       <Link href="/users">Users</Link>
//       <ProductCard></ProductCard>
//       {/* <Image
//         src="https://bit.ly/react-cover"
//         alt="next"
//         fill
//         // style={{ objectFit: "cover" }}
//         // style={{ objectFit: "contain" }}
//         className="object-cover"
//         // sizes="100vw"
//         //set mobil, table, .. sizes
//         sizes="(max-width: 480px) 100vw, (max-width: 768px) 50vw, 33vw"

//         quality={100}
//         priority>

//         </Image> */}
//     </main>
//   );
// }

// export async function generateMetadata(): Promise<Metadata> {
//   const product = await fetch("");
//   return {
//     title: product.title,
//     description: "..",
//   };
// }

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
